title:              Dev. Play
email:              yeonzzu2@gmail.com
description:        Tech Blog
author:             Joylish
baseurl:            ""
url:                "https://Joylish.github.io"
category_list: [ java, javascript, python, database, react, flask, django, operating-system, algorithm]
# Social Profiles
twitter_username:   
github_username:    Joylish
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:    # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
